# Pivot Tables

Values should be always numeric else it will give error as it performs maths calculations


General purpose spreadsheet tool that aggregates, summarizes and pivots any flat list of records using count, sums or average

It is used when you want to use your values your indexes which is not already defined

Used to create heat maps

In [1]:
import numpy as np
import pandas as pd

In [2]:
data={
    'Date': pd.date_range('2026-01-01',periods=20),
    'Product': ['A', 'B', 'C', 'D']*5, 
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['Rahul', 'Harshal', 'Amit', 'Shubham', 'Rahul', 'Harshal', 'Amit', 'Shubham', 'Rahul', 'Harshal', 'Amit', 'Shubham', 'Rahul', 'Harshal', 'Amit', 'Shubham', 'Rahul', 'Harshal', 'Amit', 'Shubham']
}

df=pd.DataFrame(data)
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+ df['Date'].dt.quarter.astype(str)

In [3]:
df

         Date Product Region  Sales  Units      Rep    Month Quarter
0  2026-01-01       A   East    200     99    Rahul  January      Q1
1  2026-01-02       B   West    817     62  Harshal  January      Q1
2  2026-01-03       C  North    523     18     Amit  January      Q1
3  2026-01-04       D  South    412     31  Shubham  January      Q1
4  2026-01-05       A   East    532     68    Rahul  January      Q1
5  2026-01-06       B   West    761     79  Harshal  January      Q1
6  2026-01-07       C  North    961     40     Amit  January      Q1
7  2026-01-08       D  South    336     33  Shubham  January      Q1
8  2026-01-09       A   East    470     57    Rahul  January      Q1
9  2026-01-10       B   West    378     60  Harshal  January      Q1
10 2026-01-11       C  North    764     72     Amit  January      Q1
11 2026-01-12       D  South    451     79  Shubham  January      Q1
12 2026-01-13       A   East    950     69    Rahul  January      Q1
13 2026-01-14       B   West    940     36  Harshal  January      Q1
14 2026-01-15       C  North    710     37     Amit  January      Q1
15 2026-01-16       D  South    479     51  Shubham  January      Q1
16 2026-01-17       A   East    515     47    Rahul  January      Q1
17 2026-01-18       B   West    135     70  Harshal  January      Q1
18 2026-01-19       C  North    302     49     Amit  January      Q1
19 2026-01-20       D  South    871     12  Shubham  January      Q1

In [4]:
#  converting A, B, C, D as columns and East, West, North and South as Regions in columns

pd.pivot_table(df,values='Sales', index='Region', columns='Product')

Product      A      B      C      D
Region
East     533.4    NaN    NaN    NaN
North      NaN    NaN  652.0    NaN
South      NaN    NaN    NaN  509.8
West       NaN  606.2    NaN    NaN

In [5]:
pvot=pd.pivot_table(df,values='Sales', index='Region', columns='Product',aggfunc='median')

In [6]:
pivot2=pd.pivot_table(df,values=['Sales','Units'], index='Region', columns='Product')

**Cross Tabs**

Cross Tabulation
Used for Counting purpose i.e. it is specialized frequency table  designed to compare categorical variables and survey data

In [7]:
ct=pd.crosstab(df['Region'],df['Product'])
ct

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0